### ISSUE TITLE
Test failure of Guile-CommonMark 0.1 with Guile 2.2.4

### ISSUE THREAD

**Issue by civodul** [OrangeShark/guile-commonmark#10]
Hello @OrangeShark!

When building version 0.1 with Guile 2.2.4, we get these test failures:

```
FAIL: tests/blocks/link-reference-definitions
=============================================

%%%% Starting test blocks link-reference-definitions  (Writing full log to "blocks link-reference-definitions.log")
tests/blocks/link-reference-definitions.scm:128: FAIL parse-blocks, link reference definition several can occur one after another
# of expected passes      11
# of unexpected failures  1
FAIL tests/blocks/link-reference-definitions.scm (exit status: 1)

FAIL: tests/inlines/links
=========================

%%%% Starting test inlines links  (Writing full log to "inlines links.log")

;;; (fail (document ((closed . #f)) (paragraph ((closed . #f)) (link ((destination . "foo\nbar") (title . #f)) (text ((closed . #t)) "link")))) #f)
tests/inlines/links.scm:99: FAIL parse-inlines, link the destination cannot contain line breaks, even if enclosed in
pointy brackets

;;; (fail (document ((closed . #f)) (paragraph ((closed . #f)) (link ((destination . "<foo\nbar>") (title . #f)) (text ((closed . #t)) "link")))) #f)
tests/inlines/links.scm:111: FAIL parse-inlines, link the destination cannot contain line breaks, even if enclosed in
pointy brackets
tests/inlines/links.scm:311: FAIL parse-inlines, link whitespace is allowed around the destination and title

;;; (fail (document ((closed . #f)) (paragraph ((closed . #f)) (text ((closed . #t)) "\">") (link ((destination . "baz") (title . #f)) (text ((closed . #t)) "bar attr=\"") (text ((closed . #t)) "<") (text ((closed . #t)) "foo ")))) #f)

;;; (fail (document ((link-references ("ref" "/uri" #f))) (paragraph ((closed . #f)) (text ((closed . #t)) "\">") (link ((destination . "/uri") (title . #f)) (text ((closed . #t)) "bar attr=\"") (text ((closed . #t)) "<") (text ((closed . #t)) "foo ")))) #f)
# of expected passes      73
# of expected failures    2
# of unexpected failures  3
FAIL tests/inlines/links.scm (exit status: 1)
```

Looking at the commit log, it seems that they might be fixed in `master`.  Do you think a 0.2 release should be tagged?

Thank you,
Ludo'.

**Comment by OrangeShark** [comment]
Was able to reproduce on Guix on the core-updates branch. I managed to narrow down the issue to the regular expression used to match "regular characters" which is `[^\x01-\x19 ()\\\\]`. This regular expression is matching the newline character `\n` in link destinations which is not allowed according to that regular expression, with newline being `\x0a` in that range.

After simplifying the regular expression I get different behaviors from guile 2.2.4 in core-updates and guile 2.2.4 in master of guix.

For guix core-updates guile, I get these:
```scheme
(define r (make-regexp "[\x01-\x19]"))

(regexp-exec r "\n") ; => #f
(regexp-exec r "\x0a") ; => #f
(regexp-exec r "\x02") ; => #("\x02" (0 . 1))
(regexp-exec r "\b") ; => #("\b" (0. 1))
(regexp-exec r "\t") ; => #f
(regexp-exec r "\r") ; => #f
```

while on guix master guile, these all match.

So this is a behavior change in how ranges are handled in regular expressions. Checking the differences between these guile, I see core-updates guile using glibc@2.28 and master guile using glibc@2.27. The [release](https://www.sourceware.org/ml/libc-alpha/2018-08/msg00003.html) for glibc@2.28 mentions:

> This update introduces significant improvements to the
> collation of Unicode characters.  This release deviates slightly from
> the standard in that the collation element ordering for lowercase and
> uppercase LATIN script characters is adjusted to ensure that regular
> expressions with ranges like [a-z] and [A-Z] don't interleave e.g. A
> is not matched by [a-z].  With the update many locales have been
> updated to take advantage of the new collation information.  The new
> collation information has increased the size of the compiled locale
> archive or binary locales.

It might be related to this. I will look more into this, but one possible solution is to not use ranges in this regular expression.

**Comment by civodul** [comment]
Woow, good catch! It does seem to be a likely culprit.

**Comment by OrangeShark** [comment]
I have just released v0.1.1 that should resolve the test failures (it also includes a fix to the build so it can install correctly with guile 2.2). I've been reading more about the regular expression ranges and there is likely more issues involved with it, not just [a-z] but also ranges like [0-9] can include other Unicode characters. I need to look further into this.

**Comment by civodul** [comment]
Hi Erik,

Thanks for the new release!  I’ve pushed the update to Guix
core-updates.

Ludo’.

**Comment by civodul** [comment]
BTW, I noticed that the release is tagged as “prerelease” in GitHub’s
API at
https://api.github.com/repos/OrangeShark/guile-commonmark/releases/13517272 .

Do you know whether/how that can be fixed?  ‘guix refresh’ currently
skips pre-releases, which is why I’m asking.
