### ISSUE TITLE
Modules get installed in PREFIX/share/share

### ISSUE THREAD

**Issue by civodul** [OrangeShark/guile-commonmark#12]
Hello!

In 0.1.1, `guile.am` contains:

```Makefile
moddir=$(datadir)/share/guile/site/$(GUILE_EFFECTIVE_VERSION)
```

It should instead be:

```Makefile
moddir=$(datadir)/guile/site/$(GUILE_EFFECTIVE_VERSION)
```

Thanks,
Ludo'.

**Comment by OrangeShark** [comment]
Hello civodul, thank you for reporting the issue. I have made a new release, v0.1.2, which fixes the installation location for the guile modules.

**Comment by civodul** [comment]
Thanks for the release!

I notice a typo:

```
commonmark/node.scm:342:44: warning: possibly unbound variable `<>'
```

There's a missing `cut` there.

Ludo'.
