### ISSUE TITLE
Something wrong with fold-node?

### ISSUE THREAD

**Issue by alezost** [OrangeShark/guile-commonmark#3]
There is a compilation warning:

```
commonmark/node.scm:342:44: warning: possibly unbound variable `<>'
```

`fold-node` procedure doesn't look correct to me (although I don't
understand it at all :-)).

Or was it mistakenly added by commit d214418a7b720e3869e5e22a291efb9005b083d6?
(as it is not used by any other procedure)

**Comment by OrangeShark** [comment]
I recall thinking I was going to use it for something else, but that eventually never happened, so I will remove it.

**Comment by alezost** [comment]
I see, BTW (srfi srfi-26) module was used only for `fold-node`, so it is not needed anymore in (commonmark node)

**Comment by OrangeShark** [comment]
Thanks, I will remove that now.
