### ISSUE TITLE
2.0 is hardcoded in Makefile.am

### ISSUE THREAD

**Issue by alezost** [OrangeShark/guile-commonmark#4]
Hello, I see that you hardcode `2.0` for the Guile dirs in
`Makefile.am`.  This is not good, as if guile-commonmark will be
compiled with Guile 2.2, for example, .scm/.go files will still be put
in 2.0 dir.

I suggest to put the following lines in `configure.ac` before
GUILE_PROGS (this will add a dependency on `pkg-config`):

```
PKG_CHECK_MODULES([GUILE], [guile-2.0 >= 2.0.11])
GUILE_PKG
```

And then you can use `$(GUILE_EFFECTIVE_VERSION)` instead of `2.0` in
`Makefile.am`, WDYT?

For more info, look at the Guile manual:
`(info "(guile) Autoconf Macros")`

And thanks for this great project!

**Comment by OrangeShark** [comment]
Thanks, I will look into it and change it.

**Comment by OrangeShark** [comment]
I tried the above and the check fails when using guile 2.2. I asked on #guile and they suggested

```
GUILE_PKG([2.2 2.0])
GUILE_PROGS([2.0.11])
```

`GUILE_PROGS` checks the min version. The `guile.m4` currently distributed in guile-2.0 has a bug where it fails for guile 2.2 but has recently been fixed, so I will include a copy of it.

**Comment by alezost** [comment]
Good to know, thanks for the info!
