### ISSUE TITLE
Better integration with emacs markdown-toc package

### ISSUE THREAD

**Issue by amirouche** [OrangeShark/guile-commonmark#6]
[markdown-toc](https://github.com/ardumont/markdown-toc) allows to generate a table of content of a given markdown document.

Right now, using it with guile-commonmark fails for two reasons:
- html comments are not supported, and md-toc use them to mark the end and start of the toc
- md-toc generates `[toc item](#fragment-link)`, but guile-commonmark doesn't generate ids for header items so the links don't work.

Here is an [example markdown document using markdown-toc](https://github.com/amirouche/Culturia/blob/master/doc/youthful-indiscretion/opencog-overview.md) and [how it is currently rendered](https://amirouche.github.io/Culturia/doc/youthful-indiscretion/opencog-overview.html).

**Comment by amirouche** [comment]
Mind the fact that I can remove the html comments manually. I don't know how do deal with the missing ids on headings.

**Comment by OrangeShark** [comment]
HTML comments will be supported once I add HTML support in general.

For generating ids for headers, it not part of the CommonMark spec, but it does seem like a very useful feature. I could possibly add a sort of option to enable this in the `commonmark->sxml` procedure.
