### ISSUE TITLE
Building on Fedora 28

### ISSUE THREAD

**Issue by humanitiesNerd** [OrangeShark/guile-commonmark#9]
On Fedora 28 x86_64 there are 2 versions  of Guile

Guile 2.0.14

and

Guile 2.2.2

Guile 2.0.14 is in /usr/bin/guile

Guile 2.2.2 is in /usr/bin/guile2.2

this is what happens

```
...
configure: checking for guile 2.2
configure: found guile 2.2
checking for guile... /usr/bin/guile
configure: error: found development files for Guile 2.2, but /usr/bin/guile has effective version 2.0

```
I'm afraid of removing guile 2.0.14 because it seems that an awful lot of stuff depends on it

How can I build guile-commonmark against guile 2.2.2 ?

On the autoconf mailing list I have been suggested a way to instruct the build system about how to use guile 2.2.2 and that works, but then /usr/bin/guild gets checked and I wonder if that is correct

They explicitly invited you to oin the thread in case you want some assistance with this, it's [here](http://lists.gnu.org/archive/html/autoconf/2018-09/msg00001.html) 

Also, why does guile gets checked 2 times ?

This is what happens with

`./configure GUILE=/usr/bin/guile2.2 --prefix=$HOME/opt
`

```
configure: checking for guile 2.2
configure: found guile 2.2
checking for guile... /usr/bin/guile2.2
checking for Guile version >= 2.0.11... 2.2.2
checking for guild... /usr/bin/guild
checking for guile-config... no

```

**Comment by OrangeShark** [comment]
On 9/22/18 1:19 AM, humanitiesNerd wrote:

> Also, why does guile gets checked 2 times ?
> 
I am using Guile's macros and the `GUILE_PKG` macro sets the version and
`GUILE_PROGS` macro finds the `GUILE` binary and other related binaries
like `GUILD`.

Looking at when you provided the `GUILE` path, it is finding the wrong
`GUILD`, checking the macro in `m4/guile.m4`, it does not take into
account version numbers... The newest version of this file in Guile does
find version numbers on these tools, but I found it had issues on Ubuntu
and Fedora. I posted about it on the guile mailing list awhile back but
didn't get any responses.

So what you want to do here is provide the path for all the tools, so it
would be `./configure GUILE=/usr/bin/guile2.2 GUILD=/usr/bin/guild2.2
--prefix=$HOME/opt`. You don't need to worry about guile-config, it not
used.

**Comment by humanitiesNerd** [comment]
> On 9/22/18 1:19 AM, humanitiesNerd wrote: Also, why does guile gets checked 2 times ?
> I am using Guile's macros and the `GUILE_PKG` macro sets the version and `GUILE_PROGS` macro finds the `GUILE` binary and other related binaries like `GUILD`. Looking at when you provided the `GUILE` path, it is finding the wrong `GUILD`, checking the macro in `m4/guile.m4`, it does not take into account version numbers... The newest version of this file in Guile does find version numbers on these tools, but I found it had issues on Ubuntu and Fedora. I posted about it on the guile mailing list awhile back but didn't get any responses. So what you want to do here is provide the path for all the tools, so it would be `./configure GUILE=/usr/bin/guile2.2 GUILD=/usr/bin/guild2.2 --prefix=$HOME/opt`. You don't need to worry about guile-config, it not used.

Than you Eric

this allowed me to build guile-commonmark

So, as far as I'm concerned, this issue can be closed.

I want to remark, though, that after building guile-commonmark I built Haunt, thhe static blogger made in Guile

It worked like a charm, found the right guile tools with no hint from me, it found the freshly built guile-commonmark

I don't know which version of the m4 macros it is using but they seem to work

I'm on fedora 28 x86_64

You might want to test it to see if it has the same issues you experienced with guile-commonmark

If it fares better, you might want to adopt its autotools setup

Thanks

**Comment by OrangeShark** [comment]
I updated master and created release v0.1.1 that should resolve this. It uses the latest m4 macro from guile. I tested this on fedora 28 and it installs without issue. You may run into issues in configuring like on my dev environment running Fedora 28 where I have both guile from Fedora but also guile from Guix. This is likely a more uncommon setup and can be resolved with something like `./configure GUILE=$(which guile)`.
